/**
 * Paiement Form Component
 * Used for creating and editing payments
 */

import { useState, useMemo } from 'react';
import type { Paiement, PaiementFormData, Prestation, ModeEncaissement } from '@/types';
import Input from '@/components/common/Input';
import Button from '@/components/common/Button';
import { isRequired } from '@/utils/validators';
import { formatDateForInput } from '@/utils/dateFormatter';
import { formatCurrency } from '@/utils/currencyFormatter';

interface PaiementFormProps {
  paiement?: Paiement;
  prestations: Prestation[];
  onSubmit: (paiement: Paiement, prestationIndices: number[]) => Promise<void>;
  onCancel: () => void;
}

const MODES_ENCAISSEMENT: ModeEncaissement[] = [
  'virement',
  'espece',
  'cheque',
  'paypal',
  'autre',
];

export default function PaiementForm({
  paiement,
  prestations,
  onSubmit,
  onCancel,
}: PaiementFormProps) {
  // Filter unpaid prestations grouped by client
  const unpaidPrestationsByClient = useMemo(() => {
    const grouped: Record<string, { prestation: Prestation; index: number }[]> = {};

    prestations.forEach((p, index) => {
      if (!p.paiement_id) {
        if (!grouped[p.nom_client]) {
          grouped[p.nom_client] = [];
        }
        grouped[p.nom_client].push({ prestation: p, index });
      }
    });

    return grouped;
  }, [prestations]);

  const [selectedClient, setSelectedClient] = useState<string>('');
  const [selectedPrestationIndices, setSelectedPrestationIndices] = useState<number[]>([]);
  const [formData, setFormData] = useState<{
    mode_encaissement: ModeEncaissement | '';
    date_encaissement: string;
    notes: string;
  }>({
    mode_encaissement: paiement?.mode_encaissement || '',
    date_encaissement: paiement?.date_encaissement
      ? formatDateForInput(paiement.date_encaissement)
      : '',
    notes: paiement?.notes || '',
  });

  const [errors, setErrors] = useState<{
    client?: string;
    prestations?: string;
  }>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Calculate total
  const total = useMemo(() => {
    return selectedPrestationIndices.reduce((sum, index) => {
      return sum + prestations[index].montant;
    }, 0);
  }, [selectedPrestationIndices, prestations]);

  const handleClientChange = (client: string) => {
    setSelectedClient(client);
    setSelectedPrestationIndices([]);
    if (errors.client) {
      setErrors((prev) => ({ ...prev, client: undefined }));
    }
  };

  const handlePrestationToggle = (index: number) => {
    setSelectedPrestationIndices((prev) => {
      if (prev.includes(index)) {
        return prev.filter((i) => i !== index);
      } else {
        return [...prev, index];
      }
    });
    if (errors.prestations) {
      setErrors((prev) => ({ ...prev, prestations: undefined }));
    }
  };

  const validateForm = (): boolean => {
    const newErrors: typeof errors = {};

    // Only validate client and prestations when creating (not editing)
    if (!paiement) {
      if (!selectedClient) {
        newErrors.client = 'Sélectionnez un client';
      }

      if (selectedPrestationIndices.length === 0) {
        newErrors.prestations = 'Sélectionnez au moins une prestation';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsSubmitting(true);

    try {
      const paiementData: Paiement = {
        reference: paiement?.reference || '', // Will be generated by DataContext
        client: paiement?.client || selectedClient, // Use existing client in edit mode
        total: paiement?.total || total, // Use existing total in edit mode
        date_encaissement: formData.date_encaissement || undefined,
        mode_encaissement: (formData.mode_encaissement as ModeEncaissement) || undefined,
        facture: paiement?.facture,
        recu: paiement?.recu,
        notes: formData.notes.trim() || undefined,
      };

      await onSubmit(paiementData, selectedPrestationIndices);
    } catch (error) {
      console.error('Form submission error:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const availableClients = Object.keys(unpaidPrestationsByClient);

  if (!paiement && availableClients.length === 0) {
    return (
      <div className="text-center py-8">
        <svg className="w-16 h-16 text-gray-400 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        <p className="text-gray-600 mb-4">
          Aucune prestation non payée disponible.
        </p>
        <Button onClick={onCancel} variant="secondary">
          Fermer
        </Button>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {/* Show client info in edit mode (read-only) */}
      {paiement && (
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 space-y-2">
          <div>
            <p className="text-xs text-gray-500">Client</p>
            <p className="text-sm font-medium text-gray-900">{paiement.client}</p>
          </div>
          <div>
            <p className="text-xs text-gray-500">Montant total</p>
            <p className="text-lg font-bold text-blue-600">{formatCurrency(paiement.total)}</p>
          </div>
          <p className="text-xs text-gray-500 italic">
            Les prestations liées ne peuvent pas être modifiées
          </p>
        </div>
      )}

      {!paiement && (
        <>
          {/* Client Selection */}
          <div>
            <label htmlFor="client" className="block text-sm font-medium text-gray-700 mb-1">
              Client <span className="text-red-500">*</span>
            </label>
            <select
              id="client"
              value={selectedClient}
              onChange={(e) => handleClientChange(e.target.value)}
              disabled={isSubmitting}
              className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors ${
                errors.client ? 'border-red-500' : 'border-gray-300'
              } ${isSubmitting ? 'bg-gray-100 cursor-not-allowed' : 'bg-white'}`}
            >
              <option value="">Sélectionner un client</option>
              {availableClients.map((client) => {
                const count = unpaidPrestationsByClient[client].length;
                return (
                  <option key={client} value={client}>
                    {client} ({count} prestation{count > 1 ? 's' : ''} non payée{count > 1 ? 's' : ''})
                  </option>
                );
              })}
            </select>
            {errors.client && (
              <p className="mt-1 text-sm text-red-600">{errors.client}</p>
            )}
          </div>

          {/* Prestations Selection */}
          {selectedClient && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Prestations à inclure <span className="text-red-500">*</span>
              </label>
              <div className="border border-gray-300 rounded-lg p-3 space-y-2 max-h-64 overflow-y-auto">
                {unpaidPrestationsByClient[selectedClient].map(({ prestation, index }) => (
                  <label
                    key={index}
                    className="flex items-start gap-3 p-2 hover:bg-gray-50 rounded cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={selectedPrestationIndices.includes(index)}
                      onChange={() => handlePrestationToggle(index)}
                      disabled={isSubmitting}
                      className="mt-1 w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                    />
                    <div className="flex-1 min-w-0">
                      <div className="flex justify-between items-start gap-2">
                        <div>
                          <p className="text-sm font-medium text-gray-900">
                            {prestation.type_prestation}
                          </p>
                          <p className="text-xs text-gray-500">
                            {prestation.date}
                          </p>
                        </div>
                        <p className="text-sm font-semibold text-blue-600 whitespace-nowrap">
                          {formatCurrency(prestation.montant)}
                        </p>
                      </div>
                    </div>
                  </label>
                ))}
              </div>
              {errors.prestations && (
                <p className="mt-1 text-sm text-red-600">{errors.prestations}</p>
              )}
            </div>
          )}
        </>
      )}

      {/* Total */}
      {(paiement || selectedPrestationIndices.length > 0) && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="flex justify-between items-center">
            <span className="text-sm font-medium text-gray-700">Total du paiement:</span>
            <span className="text-2xl font-bold text-blue-600">
              {formatCurrency(paiement?.total || total)}
            </span>
          </div>
        </div>
      )}

      {/* Encaissement Section (Optional) */}
      {(paiement || selectedPrestationIndices.length > 0) && (
        <div className="border-t pt-4">
          <h3 className="text-sm font-medium text-gray-700 mb-3">
            Encaissement (optionnel)
          </h3>

          <div className="space-y-4">
            {/* Date Encaissement */}
            <Input
              label="Date d'encaissement"
              type="date"
              value={formData.date_encaissement}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, date_encaissement: e.target.value }))
              }
              disabled={isSubmitting}
            />

            {/* Mode Encaissement */}
            <div>
              <label htmlFor="mode_encaissement" className="block text-sm font-medium text-gray-700 mb-1">
                Mode d'encaissement
              </label>
              <select
                id="mode_encaissement"
                value={formData.mode_encaissement}
                onChange={(e) =>
                  setFormData((prev) => ({
                    ...prev,
                    mode_encaissement: e.target.value as ModeEncaissement | '',
                  }))
                }
                disabled={isSubmitting}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white"
              >
                <option value="">Sélectionner un mode</option>
                {MODES_ENCAISSEMENT.map((mode) => (
                  <option key={mode} value={mode}>
                    {mode.charAt(0).toUpperCase() + mode.slice(1)}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>
      )}

      {/* Notes */}
      {(paiement || selectedPrestationIndices.length > 0) && (
        <div>
          <label htmlFor="notes" className="block text-sm font-medium text-gray-700 mb-1">
            Notes
          </label>
          <textarea
            id="notes"
            value={formData.notes}
            onChange={(e) =>
              setFormData((prev) => ({ ...prev, notes: e.target.value }))
            }
            disabled={isSubmitting}
            rows={2}
            placeholder="Commentaires optionnels..."
            className={`w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors resize-none ${
              isSubmitting ? 'bg-gray-100 cursor-not-allowed' : 'bg-white'
            }`}
          />
        </div>
      )}

      <div className="flex gap-3 pt-4">
        <Button type="submit" variant="primary" disabled={isSubmitting} fullWidth>
          {isSubmitting ? 'Création...' : paiement ? 'Mettre à jour' : 'Créer le paiement'}
        </Button>
        <Button type="button" variant="secondary" onClick={onCancel} disabled={isSubmitting}>
          Annuler
        </Button>
      </div>
    </form>
  );
}
